Add os-must-gather under operator line required project
It will fix the following error:
```
Error: Project github.com/openstack-k8s-operators/openstack-must-gather does not have the default branch master
```

Change-Id: I654245573329f9b79b9208cbf4541f78dd62d4fc
Signed-off-by: Chandan Kumar <chkumar@redhat.com>