Update patch set 8
Patch Set 8:

virtualenv creation fails with AttributeError: 'NoneType' object has no attribute 'version_tuple', some recent change in c9-stream seems caused it. Error raised at https://github.com/pypa/virtualenv/blob/0262fa6d9a0f8b45c80e6b2f82109ab1250ec336/src/virtualenv/seed/embed/via_app_data/via_app_data.py#L43

seems installation from pip working, try to update with it and see. Recently tripleo jobs were also impacted and fixed it like https://review.opendev.org/c/openstack/tripleo-ci/+/820172

Patch-set: 8