Add task to create symlink for /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
CS10 rpmbuild is failing with following error[1]
```
Error in build_rpm_wrapper for python-taskflow: Could not find a
suitable TLS CA certificate bundle,
invalid path: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
```

Based on local debugging, we found following thing
```
[root@0453130b20e2 /]# rpm -qf /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
error: file /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt: No such file or directory
[root@0453130b20e2 /]# dnf install ca-certificates
CentOS Stream 10 - BaseOS                                                                                                                 961 kB/s | 6.6 MB     00:07
CentOS Stream 10 - AppStream                                                                                                              645 kB/s | 3.2 MB     00:05
CentOS Stream 10 - Extras packages                                                                                                        5.0 kB/s | 6.1 kB     00:01
Package ca-certificates-2024.2.69_v8.0.303-102.3.el10.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

Since this path does not exists on CS10, symlink needs to be created
to make it working.

Links:
[1]. https://logserver.rdoproject.org/726/rdoproject.org/726b87c95d9a48c58a13677b4a90692a/buildset/centos10/repos/32/a8/32a8d2571f760d6de9014f7c122a4f57eb372772_dev/rpmbuild.log.gz
Change-Id: I2a9a70bfbb7e138eebd420f827b24dbfce4aa1bf
Signed-off-by: Chandan Kumar (raukadah) <chkumar@redhat.com>